AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Sheet2Markdown SAM Stack

Globals:
  Function:
    Timeout: 3

Resources:

  Sheet2MarkdownApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      EndpointConfiguration: REGIONAL
      MethodSettings:
        - HttpMethod: "POST"
          ResourcePath: "/markdown"
          ThrottlingRateLimit: 2000
          ThrottlingBurstLimit: 1000
      DefinitionBody:
        'Fn::Transform':
          Name: 'AWS::Include'
          Parameters:
            Location: './api.yaml'

  Sheet2MarkdownFunction:
    Type: AWS::Serverless::Function 
    Properties:
      PackageType: Image
      ImageUri: sheet2markdown:latest
    Metadata:
      Dockerfile: Dockerfile
      DockerContext: ./
      DockerTag: latest
      
  Sheet2MarkdownFunctionPermission:
    Type: "AWS::Lambda::Permission"
    DependsOn:
    - Sheet2MarkdownApi
    - Sheet2MarkdownFunction
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref Sheet2MarkdownFunction
      Principal: apigateway.amazonaws.com

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  Sheet2MarkdownApi:
    Description: "API Gateway endpoint URL for Prod stage"
    Value: !Sub "https://${Sheet2MarkdownApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
  Sheet2MarkdownFunction:
    Description: "Sheet 2 Markdown Lambda Function ARN"
    Value: !GetAtt Sheet2MarkdownFunction.Arn
  Sheet2MarkdownIamRole:
    Description: "Implicit IAM Role created for Sheet 2 Markdown function"
    Value: !GetAtt Sheet2MarkdownFunction.Arn
